import Database from 'better-sqlite3';
import path from 'path';
import fs from 'fs'; // Added fs import
import { fileURLToPath } from 'url';
// import { graduates as staticGraduates } from '../src/data/static/graduates.ts'; // Removed direct import
import type { Graduate } from '../src/types/college.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const dbPath = path.resolve(__dirname, '../src/data/database.db');
const db = new Database(dbPath);

console.log('🚀 Starting graduates data migration...');

try {
    // Read the content of graduates.ts
    const graduatesFilePath = path.resolve(__dirname, '../src/data/static/graduates.ts');
    const fileContent = fs.readFileSync(graduatesFilePath, 'utf-8');

    // Extract the graduates array string
    const graduatesArrayMatch = fileContent.match(/export const graduates: Graduate\[] = (\[[\s\S]*?\]);/);
    if (!graduatesArrayMatch || !graduatesArrayMatch[1]) {
        throw new Error('Could not extract graduates array from static/graduates.ts');
    }
    let graduatesArrayString = graduatesArrayMatch[1];

    // --- Transform the string into valid JSON ---
    // Remove 'id:' from objects if present, as it will be autogenerated or handled from other properties.
    // This is a simplification; a more robust parser might be needed for complex cases.
    graduatesArrayString = graduatesArrayString.replace(/id: "(.*?)"(?=,)/g, '"_id_placeholder_": "$1"');
    
    // Replace asset(...) with just the path string inside double quotes
    graduatesArrayString = graduatesArrayString.replace(/asset\((.*?)\)/g, (match, p1) => p1.trim());

    // Replace single quotes with double quotes for JSON parsing
    graduatesArrayString = graduatesArrayString.replace(/'/g, '"');
    
    // Add quotes around unquoted keys (e.g., name: "Value" -> "name": "Value")
    graduatesArrayString = graduatesArrayString.replace(/(\w+):/g, '"$1":');

    // Manually handle the comments if they exist.
    // Remove JS comments (// ...) and multiline comments (/* ... */)
    graduatesArrayString = graduatesArrayString.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
    
    // Replace trailing commas if any (JSON doesn't allow them)
    graduatesArrayString = graduatesArrayString.replace(/,\s*([\]}])/g, '$1');
    // --- End Transformation ---
    
    // Parse the string into a JavaScript object
    const staticGraduates: Graduate[] = JSON.parse(graduatesArrayString);

    // Clear existing graduates data to prevent duplicates on re-run
    db.prepare('DELETE FROM graduates').run();
    console.log('✅ Cleared existing data from "graduates" table.');

    const insertStmt = db.prepare(`
        INSERT INTO graduates (id, name, graduation_year, position, workplace, image_src, bio, is_featured)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    `);

    for (const graduate of staticGraduates) {
        // Adjust image_src for database storage
        let image_src = graduate.image || null;
        if (image_src) {
            // Remove '/public' prefix if it exists, as it's added by asset() but not needed in DB path
            image_src = image_src.replace(/^\/public/, '');
            // Ensure path starts with /vipuskniki or /Diploms etc.
            if (!image_src.startsWith('/')) {
                image_src = '/' + image_src;
            }
        }
        
        const is_featured = graduate.isFeatured ? 1 : 0;

        insertStmt.run(
            graduate.id, // Use the provided ID for migration, as it's in the static data
            graduate.name,
            graduate.graduationYear,
            graduate.position || null,
            graduate.workplace || null,
            image_src,
            graduate.bio || null,
            is_featured
        );
    }

    console.log(`🎉 Successfully migrated ${staticGraduates.length} graduate records.`);
} catch (error) {
    console.error('❌ Error during graduates data migration:', error);
} finally {
    db.close();
    console.log('Database connection closed.');
}
